# Generated by Django 2.1.5 on 2019-01-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('category', models.TextField()),
                ('title', models.TextField()),
                ('keywords', models.TextField()),
                ('opt_id', models.TextField()),
            ],
        ),
    ]
