# Generated by Django 2.1.5 on 2019-01-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
