# Generated by Django 2.1.5 on 2019-01-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiz', '0002_item_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
