# Generated by Django 2.1.5 on 2019-01-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiz', '0003_auto_20190119_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='body',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(),
        ),
    ]
