# Generated by Django 2.1.5 on 2019-01-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiz', '0004_auto_20190119_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='body',
            field=models.TextField(),
        ),
    ]
